# Generated by Django 5.2.8 on 2026-01-01 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_accept_orders', models.BooleanField(default=False, help_text='Automatically accept incoming orders')),
                ('show_timer', models.BooleanField(default=True, help_text='Show elapsed time on orders')),
                ('warning_time_minutes', models.PositiveIntegerField(default=15, help_text='Minutes until order shows warning color')),
                ('critical_time_minutes', models.PositiveIntegerField(default=30, help_text='Minutes until order shows critical color')),
                ('sound_enabled', models.BooleanField(default=True, help_text='Play sound on new orders')),
                ('stations_enabled', models.BooleanField(default=False, help_text='Enable kitchen stations')),
            ],
            options={
                'verbose_name': 'Kitchen Configuration',
                'verbose_name_plural': 'Kitchen Configuration',
            },
        ),
        migrations.CreateModel(
            name='KitchenStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='#3880ff', help_text='Hex color for station display', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kitchen Station',
                'verbose_name_plural': 'Kitchen Stations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KitchenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(db_index=True, help_text='Reference to the sale in sales module', max_length=100)),
                ('table_id', models.PositiveIntegerField(blank=True, help_text='Reference to table if from tables module', null=True)),
                ('table_number', models.CharField(blank=True, default='', help_text='Table number for display', max_length=20)),
                ('order_number', models.CharField(db_index=True, help_text='Display order number', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = higher priority')),
                ('notes', models.TextField(blank=True, default='', help_text='Special instructions for kitchen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kitchen Order',
                'verbose_name_plural': 'Kitchen Orders',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='kitchen_kit_status_f3da57_idx')],
            },
        ),
        migrations.CreateModel(
            name='KitchenOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('modifiers', models.TextField(blank=True, default='', help_text="Modifiers like 'no onions', 'extra cheese'")),
                ('notes', models.TextField(blank=True, default='', help_text='Special instructions for this item')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.kitchenorder')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='kitchen.kitchenstation')),
            ],
            options={
                'verbose_name': 'Kitchen Order Item',
                'verbose_name_plural': 'Kitchen Order Items',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
