# Generated by Django 6.0.1 on 2026-02-09 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenOrderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('action', models.CharField(choices=[('received', 'Received'), ('accepted', 'Accepted'), ('started', 'Started'), ('bumped', 'Bumped'), ('completed', 'Completed'), ('served', 'Served'), ('recalled', 'Recalled'), ('cancelled', 'Cancelled'), ('priority_changed', 'Priority Changed')], max_length=20, verbose_name='Action')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kitchen Order Log',
                'verbose_name_plural': 'Kitchen Order Logs',
                'db_table': 'kitchen_order_log',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KitchenSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('auto_accept_orders', models.BooleanField(default=False)),
                ('show_timer', models.BooleanField(default=True)),
                ('warning_time_minutes', models.PositiveIntegerField(default=15)),
                ('critical_time_minutes', models.PositiveIntegerField(default=30)),
                ('items_per_page', models.PositiveIntegerField(default=12)),
                ('auto_refresh_seconds', models.PositiveIntegerField(default=10)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('sound_on_new_order', models.BooleanField(default=True)),
                ('sound_on_rush', models.BooleanField(default=True)),
                ('auto_bump_enabled', models.BooleanField(default=False)),
                ('auto_bump_delay_seconds', models.PositiveIntegerField(default=5)),
                ('color_coding_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kitchen Settings',
                'verbose_name_plural': 'Kitchen Settings',
                'db_table': 'kitchen_settings',
                'abstract': False,
            },
        ),
    ]
