# Generated by Django 6.0.1 on 2026-02-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('kitchen', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenorderlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_logs', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='kitchenorderlog',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_logs', to='orders.orderitem', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='kitchenorderlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_actions', to='accounts.localuser', verbose_name='Performed By'),
        ),
        migrations.AddField(
            model_name='kitchenorderlog',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_logs', to='orders.kitchenstation', verbose_name='Station'),
        ),
        migrations.AlterUniqueTogether(
            name='kitchensettings',
            unique_together={('hub_id',)},
        ),
    ]
